Repository m-chugaev/teach-web, pull requests merged in 2024-02, with the labels that each got.

#20 Лекция3
  lecture03/basic/Harin/index.html
Labels: error

#19 trebunskih
  lecture03/basic/trebunskih/css/style.css
  lecture03/basic/trebunskih/index.html
Labels: draft

#24 Реализовано задание лекции 3
  lecture03/advanced/chugaev/index.html
Labels: done

#13 Задание лекция 2
  lecture02/basic/gladkov/index.html
Labels: error

#22 добавил 10 свойств
  lecture03/basic/britvin/index.html
Labels: error

#34 update
  lecture04/advanced/index.js
  package.json
Labels: done

#9 Spesivtsev Vladimir
  lecture02/advanced/spesivtsev/graph.png
  lecture02/advanced/spesivtsev/index.html
Labels: error

#29 start4Lab
  lecture04/basic/trebunskih/graph.png
  lecture04/basic/trebunskih/index.html
Labels: error
